version: '3'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  admin:
    build: ./admin
    links:
      - rabbitmq
    ports:
      - "8001:8001"
    depends_on:
      - admindb

  admindb:
    image: mysql:5.7
    platform: linux/x86_64
    expose:
      - "3308"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: node_admin
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot
    volumes:
      - admindb_data:/var/lib/mysql

  main:
    build: ./main
    links:
      - rabbitmq
    ports:
      - "8002:8002"
    depends_on:
      - maindb

  maindb:
    image: mysql:5.7
    platform: linux/x86_64
    expose:
      - "3307"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: node_main
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot
    volumes:
      - maindb_data:/var/lib/mysql

volumes:
  admindb_data:
  maindb_data:
